option('cachedir',
       type : 'string',
       value : '/var/cache/pkgfile',
       description : 'default directory to store pkgfile data')

option('systemd_units',
       type : 'boolean',
       value : true,
       description : 'install systemd units to system unit directory')

option('unittests', type : 'feature', value : 'auto',
       description : 'Include unit tests in the build. Depends on gtest and gmock.')
