#!/bin/bash -le

cd /github/workspace

# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

pacman -Syu --noconfirm base-devel git gmock gtest python meson pcre

# build
meson build --prefix=/usr --buildtype=debugoptimized -Db_sanitize=address
ninja -C build

# test
meson test -C build

# install
ninja -C build install
