#!/bin/bash -le

pacman -Syu --noconfirm base-devel git gmock gtest python meson pcre perl

# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile

# build
meson setup build --prefix=/usr --buildtype=debugoptimized
ninja -C build

# test
meson test -C build

# install
ninja -C build install
